version: 2.1

jobs:
  sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/openjdk:17.0
    resource_class: small
    steps:
      - checkout:
          path: ~/build/repo
      - run:
          name: Verify Java Installation
          command: |
            java -version
            echo $JAVA_HOME
      - run:
          name: Download Sonar Scanner
          command: curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - run:
          name: Unzip Sonar Scanner
          command: unzip sonar-scanner.zip
      - run:
          name: Move Sonar Scanner
          command: mv sonar-scanner-4.7.0.2747-linux sonar-scanner
      - run:
          name: Add sonar-scanner to PATH
          command: |
            echo 'export PATH="$PATH:$(pwd)/sonar-scanner/bin"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify Java Version Before Scanner
          command: |
            source $BASH_ENV
            java -version
            echo $JAVA_HOME
      - run:
          name: Run Sonar Scanner
          command: |
            source $BASH_ENV
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH="$JAVA_HOME/bin:$PATH"
            java -version
            sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="${CIRCLE_BRANCH:-master}" \
            -Dsonar.sources="."

workflows:
  build-and-test:
    jobs:
      - sonarqube
