version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  test-node:
    executor: node/default
    working_directory: ~/project/frontend
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests with coverage
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit --coverage
      - run:
          name: Create coverage directory for SonarQube
          command: mkdir -p ~/build/repo/coverage
      - run:
          name: Move coverage results to SonarQube
          command: cp -R coverage/* ~/build/repo/coverage/
      - store_test_results:
          path: ./test-results/

  build-node:
    executor: node/default
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: |
            CI=false npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/openjdk:17.0
    resource_class: small
    steps:
      - checkout:
          path: ~/build/repo
      - run:
          name: Verify Java Installation
          command: |
            java -version
            echo $JAVA_HOME
      - run:
          name: Download Sonar Scanner
          command: curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - run:
          name: Unzip Sonar Scanner
          command: unzip sonar-scanner.zip
      - run:
          name: List Files
          command: ls
      - run:
          name: Move Sonar Scanner
          command: mv sonar-scanner-5.0.1.3006-linux sonar-scanner
      - run:
          name: Update Sonar Scanner Properties
          command: |
            echo 'sonar.java.home=/usr/local/jdk-17.0.12' >> ~/build/sonar-scanner/conf/sonar-scanner.properties
      - run:
          name: Add sonar-scanner to PATH
          command: |
            echo 'export PATH="$PATH:$(pwd)/sonar-scanner/bin"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify Java Version Before Scanner
          command: |
            source $BASH_ENV
            java -version
            echo $JAVA_HOME
      - run:
          name: Run Sonar Scanner
          command: |
            source $BASH_ENV
            export JAVA_HOME=/usr/local/jdk-17.0.12
            export PATH="$JAVA_HOME/bin:$PATH"
            java -version
            sonar-scanner -X \
            -Dsonar.java.home="$JAVA_HOME" \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="${CIRCLE_BRANCH:-master}" \
            -Dsonar.sources="."
            -Dsonar.coverageReportPaths=coverage/lcov.info

workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
      - sonarqube
